module.exports = {
    tabWidth: 2,
    semi: true,
    singleQuote: false,
    trailingComma: "es5",
    printWidth: 80,
    bracketSpacing: true,
    arrowParens: "always",
    endOfLine: "lf",
    useTabs: false,
    quoteProps: "as-needed",
    insertPragma: false,
    requirePragma: false,
    rangeStart: 0,
    rangeEnd: Infinity,
};
